[general]
live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "FiraMonoNerdFont"
style = "Regular"

[env]
TERM = "alacritty"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"

[window]
decorations = "none"
dynamic_padding = false
opacity=0.75

[window.padding]
x = 0
y = 0

[colors.primary]
background = "#111111"
foreground = "#eeeeee"

[colors.bright]
black = "#000000"
blue = "0x49a4f8"
cyan = "0x99faf2"
green = "0xc0e17d"
magenta = "0xa47de9"
red = "0xec5357"
white = "0xffffff"
yellow = "0xf9da6a"

[colors.normal]
black = "0x2e2e2e"
blue = "0x47a0f3"
cyan = "0x64dbed"
green = "0xabe047"
magenta = "0x7b5cb0"
red = "0xeb4129"
white = "0xe5e9f0"
yellow = "0xf6c744"
